apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketdex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketdex
  template:
    metadata:
      labels:
        app: rocketdex
    spec:
      containers:
      - name: rocketdex
        image: ghcr.io/danylo-gavrylovskyi/gh-actions:c6eb0f4
        ports:
        - containerPort: 8080
