apiVersion: v1
kind: Service
metadata:
  name: rocketdex-service
spec:
  selector:
    app: rocketdex
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
